#!/bin/sh 

## @file mc_con_ftp
## @brief Lanzar mc con dirección ftp del proyecto

terminal='xterm -geometry 150x50 -bg black -fg white -e '
comando_mc='mc ftp://${mt_ftp}/${mt_ftp_directorio}'

if [ -z "$mt_ftp" ] ; then
   echo
   echo No tenemos configurado ningún ftp en este proyecto
   echo
else
   comando_mc="`eval echo "$comando_mc"`"
   echo 
   echo "Comando: $terminal '$comando_mc'"
   echo
   eval "$terminal '$comando_mc'" 
fi
