#!/bin/bash 

## @file comprobar_enlaces_rotos
## @brief Comprobación de los enlaces de un dominio web
##
## dependencias: curl, lynx, wget

help() { doxygen2help "$0" ; }

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

if [ -z "$1" ] ; then
   # miramos si el directorio actual es un proyecto con su configuración
   source "`dirname "$BASH_SOURCE"`/../config"
   if [ -z "$mt_url_servidor" ] ; then
      echo
      echo Es necesario la url para poder ser analizada
      echo
      tecla
      exit 1
   else
      url="$mt_url_servidor"
   fi
else
   url="$1"
fi

# file_tmp="/tmp/comprobar_enlaces_rotos"
# 
# wget --spider -r -l2 -nv "$url" | tee -a "$file_tmp"

if [ $# -eq 2 ];
   then
   echo -e "$Usage $0 URL\n"
   exit -1;
fi

echo
echo Buscando enlaces rotos
echo ----------------------
echo
echo url: $url
echo

mkdir /tmp/$$.lynx
cd /tmp/$$.lynx
# lynx -traversal $url > /dev/null
lynx -traversal http://$url
count=0;
sort -u reject.dat > links.txt
while read link;
do
output=`curl -I $link -s | grep "HTTP/.*OK"`;
if [[ -z $output ]];
then
echo $link;
let count++
fi
done < links.txt
if [ $count -eq 0 ] ; then
   echo
   echo Sin enlaces rotos
   echo
else
   echo
   echo $count enlaces rotos
   echo
fi

read
