#!/bin/bash

## @file informacion_ip
## @brief Mostrar información sobre una ip o un dominio.

help() { doxygen2help "$0" ; }

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

informacion_ip_IP="$1"
informacion_ip_CMD=/home/eduardo/opt/automater/Automater.py

if [ "$informacion_ip_IP" = "" ] ; then

   echo
   read -p "URL o IP: " OPCION
   if [ "$OPCION" != "" ] ; then
      informacion_ip_IP="$OPCION"
   fi

fi

if [ "$informacion_ip_IP" != "" ] ; then

  echo
  echo Información geográfica
  echo
  echo curl ipinfo.io/$informacion_ip_IP
  echo
  curl ipinfo.io/$informacion_ip_IP

  echo
  echo Automater.py
  echo
  echo $informacion_ip_CMD -t $informacion_ip_IP
  echo
  $informacion_ip_CMD -t "$informacion_ip_IP"
fi
