#!/bin/sh

## @file permisos_www-data
## @brief Cambiar permisos para los proyectos web, para que no den problemas
##
## Hacer que el grupo de la carpeta del proyecto sea www-data
## y dar permisos de escritura al grupo
##
## $1 Carpeta del proyecto

proyecto=$1
usuario=$USER

sudo chown -R www-data:${usuario} "$proyecto"

sudo chmod -R 775 "$proyecto"
