#!/bin/bash

## @file script2md
##
## @brief Construir salida markdown en base a la salida de doxygen2help.

help() { doxygen2help "$0" ; }

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

DIRNAME=`basename $PWD`

head() {

    declare PWD=`pwd`
    declare BRIEF=''
    declare DIR_ACTUAL=`pwd`
    declare PRE_FILE="$1"

    [[ "$1" != "" ]] && cd "$1"

    for s in `ls` ; do
        [[ "$s" == "readme.md" ]] && continue
        if [ -d "$s" ] ; then
            head $s
            continue
        fi
        [[ ! -e "$s" ]] && continue
        BRIEF=`cat $s | grep -m 1 '@brief' | cut -d' ' -f 3-`
        echo -e "- [**${PRE_FILE}/${s}**](#${s})\t$BRIEF"
    done
    cd "$DIR_ACTUAL"
}

help2md() {
    
    declare HELP=''
    declare DIR_ACTUAL=`pwd`
    declare PRE_FILE="$1"

    [[ "$1" != "" ]] && cd "$1"

    for s in `ls` ; do
        [[ ! -x "$s" ]] && continue
        if [ -d "$s" ] ; then
            help2md "$s"
            continue
        fi
        HELP="`./$s --help`"
        if [ "$HELP" != "" ] ; then
            echo "<a name=\"$s\"/>"
            echo
            echo "### ${PRE_FILE}/${s}"
            echo
            echo '```'
            echo -e "$HELP"
            echo '```'
            echo
        fi
    done
    cd "$DIR_ACTUAL"
}

if [ -e ".head.md" ] ; then
    cat .footer.md
else
    echo "# $DIRNAME"
    echo
fi

echo
echo -e "## Listado"
echo
head .

echo
echo -e "## Scripts"
echo
help2md .

if [ -e ".footer.md" ] ; then
    cat .footer.md
fi
