#!/bin/bash

## @file registros
##
## Para que funcione se debe configurar mysql con las siguientes instrucciones.
## 
##  # Here you can see queries with especially long duration
##  log_slow_queries        = /var/log/mysql/mysql-slow.log
##  long_query_time = 2
##  log-queries-not-using-indexes

## @var mysql_log
## Archivo de registro

mysql_log=/var/log/mysql/mysql-slow.log

xterm -bg black -fg yellow  -maximized -e "grc tail -f $mysql_log" &
